# Amazon settings -- you'll need an Amazon Payments account, sign up here --> http://bit.ly/SGksTv
amazon_access_key: "XXXX"
amazon_secret_key: "XXXX"

# Paypal settings
paypal_username: "XXXX"
paypal_password: "XXXX"
paypal_signature: "XXXX"

# if use_payment_options is set to true, then a set of radio buttons will be displayed with various payment options.
# There is a PaymentOption model for storing info about payment options.  To set up your payment options you should
# put code in seeds.rb, then run rake db:seed
use_payment_options: true

# Amazon limits how much we can charge people with their Multi-Use tokens.
# You probably should add some leeway to account for international shipping
# this value will be added to the price to create a charge limit
charge_limit: 25.00

# Stats settings
primary_stat: "orders"

# This'll show up in the tweet as, "I'm order number ..."
primary_stat_verb: 'order'

# The 2nd call to action button
middle_reserve_text: "Order Now"

# Call to action section

# Text for user to see about shipping, for example: "Ships within 48 hours"
ships: "Ships Next Day"

call_to_action: "Order Now"

# The paragraph below the price. You'd probably say something about how you're not going to charge them before it ships (so it's less risky).
warrenty_message: "Satisfaction guaranteed with a limited warranty."

# Social Stuff
facebook_app_id: "1234567890"

# Google Analytics
google_id: "1234567890"
